---
- name: "Assert usage of systemd as an init system"
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"
  tags:
    - enduro_install
    - enduro_configure
    - enduro_run
    - temporal_install
    - temporal_configure
    - temporal_run

- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - enduro_install
    - enduro_configure
    - enduro_run
    - temporal_install
    - temporal_configure
    - temporal_run

- import_tasks: preflight-enduro.yml
  when: not enduro_install_rpm|bool
  tags:
    - enduro_install
    - enduro_configure
    - enduro_run

- import_tasks: preflight-temporal.yml
  when: not temporal_install_rpm|bool
  tags:
    - temporal_install
    - temporal_configure
    - temporal_run

- import_tasks: preflight-tctl.yml
  when: not tctl_install_rpm|bool
  tags:
    - tctl_install

- import_tasks: install-temporal.yml
  when: not temporal_install_rpm|bool
  become: true
  tags:
    - temporal_install

- import_tasks: install-tctl.yml
  when: not tctl_install_rpm|bool
  become: true
  tags:
    - tctl_install

- import_tasks: install-temporal-rpm.yml
  when: temporal_install_rpm|bool
  become: true
  tags:
    - temporal_install

- import_tasks: install-tctl-rpm.yml
  when: tctl_install_rpm|bool
  become: true
  tags:
    - tctl_install

- import_tasks: configure-temporal.yml
  become: true
  tags:
    - temporal_configure

- import_tasks: install-enduro.yml
  when: not enduro_install_rpm|bool
  become: true
  tags:
    - enduro_install

- import_tasks: install-enduro-rpm.yml
  when: enduro_install_rpm|bool
  become: true
  tags:
    - enduro_install

- import_tasks: configure-enduro.yml
  become: true
  tags:
    - enduro_configure

- name: Ensure services are enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: "{{ item }}"
    enabled: true
    state: "restarted"
  with_items:
    - enduro
    - temporal
  tags:
    - enduro_run
